# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کارشناس',
                'verbose_name_plural': 'کارشناسان',
            },
        ),
        migrations.CreateModel(
            name='ImageNGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='NGO/Gallery', verbose_name='فایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس های گالری',
            },
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('latin_name', models.CharField(max_length=100, unique=True, verbose_name='نام لاتین')),
                ('continent', models.CharField(choices=[('NORTH_AMERICA', 'آمریکای شمالی'), ('SOUTH_AMERICA', 'آمریکای جنوبی'), ('ASIA', 'آسیا'), ('EUROPE', 'اروپا'), ('AFRICA', 'افریقا'), ('AUSTRALIA', 'استرالیا')], max_length=30)),
                ('flag', models.ImageField(upload_to='NGO/flags', verbose_name='پرچم')),
                ('about_country', models.TextField(verbose_name='درباره کشور')),
                ('about_NGO', models.TextField(verbose_name='درباره انجمن')),
            ],
            options={
                'verbose_name': 'انجمن دوستی',
                'verbose_name_plural': 'انجمن ها',
            },
        ),
        migrations.AddField(
            model_name='imagengo',
            name='NGO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='persons.NGO'),
        ),
        migrations.AddField(
            model_name='expert',
            name='NGO',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.NGO'),
        ),
        migrations.AddField(
            model_name='expert',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
