# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='flag',
            field=models.ImageField(upload_to=persons.models.NGO.get_path, verbose_name='پرچم'),
        ),
    ]
