# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('show_it', models.BooleanField(verbose_name='نشان داده شود')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('random_int', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('shortDescription', models.CharField(max_length=200, verbose_name='شرح مختصر')),
                ('text', models.TextField(verbose_name='متن')),
                ('picture', models.ImageField(help_text='فرمت عکس باید با پسوند png باشد', upload_to='News/pictures', verbose_name='عکس خبر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('NOT_SPECIFIED', 'نامعلوم'), ('VERY_IMPORTANT', 'خیلی مهم'), ('IMPORTANT', 'مهم'), ('NOT_IMPORTANT', 'مهم نیست')], help_text='خبر های خیلی مهم در اسلایدر صفحه اصلی نشان داده می شوند\n!خبر های مهم در صفحه اصلی و در زیر اسلایدر به نمایش در خواهند امد\n!خبر هایی که مهم نیستند در صفحه اصلی نشان داده نمی شوند', max_length=30, verbose_name='وضعیت')),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.NGO')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='News',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
